import 'dart:convert';
import 'package:embrance/jobs/Courses.dart';
import 'package:embrance/network/constants.dart';
import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';

import '../network/RestAPI.dart';
import 'job_details_entity.dart';
import 'jobs_entity.dart';



class RoadMapController extends GetxController{

  ScrollController scrollController = ScrollController();

  final RestAPI restAPI = Get.find<RestAPI>();
  List<JobDetailsEntity> jobsDetails = <JobDetailsEntity>[].obs;
  List<Courses> courseList = <Courses>[].obs;

  List<Courses> listOne = <Courses>[].obs;
  List<Courses> listTwo = <Courses>[].obs;
  List<Courses> listThree = <Courses>[].obs;
  List<Courses> listFour = <Courses>[].obs;
  List<Courses> listFive = <Courses>[].obs;

  var isDataLoading = false.obs;
  var name = "".obs;

  @override
  void onInit() {
    loadCourse();
    super.onInit();
  }



  @override
  void onClose() {
    super.onClose();
  }

  void loadCourse(){
    courseList.add(Courses(category: "Computer Science",subcategory: "Design", no: "CSC 1", name: "Introduction to Computer Science", prerequisite: "Intermediate algebra.", semester: "Fall, Spring", skills: "Fundamental concepts of computers, computation and programming; history and principles of computing; problem solving; input, output; data representation, storage, and file organization; computer hardware, networking and data communication; social, economic and ethical implications; computer security and privacy. Students will solve problems using a programming language. Lecture, two hours; technical activity and laboratory, two hours."));
    courseList.add(Courses(category: "Computer Science",subcategory: "Design", no: "CSC 155", name: "Advanced Computer Graphics", prerequisite: "CSC 133", semester: "Fall only", skills: "Modeling, viewing, and rendering techniques in 3D computer graphics systems. Topics include modeling systems and data structures; polygonal and parametric surface representation; transformations, windowing, clipping and projections in 3D; hidden surface removal algorithms; techniques for realism such as shading, shadows, highlights, and texture; fractals and procedural models; introduction to animation; hardware support for computer graphics; and the application of graphics principles to virtual reality systems and 3D games."));
    courseList.add(Courses(category: "Computer Science",subcategory: "Design", no: "CSC 148", name: "Modeling and Experimental Design", prerequisite: "MATH 26B or MATH 31, STAT 50 or ENGR 115, and proficiency in a programming language.", semester: "Not offered", skills: "Modeling and simulation techniques; Monte Carlo methods; queuing theory; model formulation, data collection and analysis, experimental design; model verification and validation."));
    courseList.add(Courses(category: "Computer Engineering",subcategory: "Design", no: "CPE 186", name: "Computer Hardware System Design", prerequisite: "CPE 185 or EEE 174", semester: "Fall, Spring", skills: "Study of Intel and Motorola architectures, bus structures, interrupts, memory interface and controllers, bus arbitration, DMA controllers, I/O interface, bridges and microcontroller. Electromagnetic compatibility and regulations, cabling and shielding, grounding, digital circuit noise and layout."));
    courseList.add(Courses(category: "Computer Engineering",subcategory: "Design", no: "CPE 187", name: "Embedded Systems Design", prerequisite: "CPE 185 or EEE 174", semester: "Fall, Spring", skills: "Introduction to embedded systems with applied projects. The ISA, memory map, register architecture and configuration for one processor are studied in depth. Topics include: Overview of embedded systems; hardware, firmware, and software design; interrupt programming; application of contemporary interfacing protocols like USB and Bluetooth; use of an integrated development environment (IDE) for development; functional debugging; Real Time Operating Systems (RTOS) considerations and scheduling. One two hour lecture and one three hour lab per week."));
    courseList.add(Courses(category: "Computer Engineering",subcategory: "Design", no: "CPE 151", name: "CMOS and Digital VLSI Design", prerequisite: "CPE 64 and EEE 108", semester: "Fall, Spring", skills: "Introduction to CMOS logic gates and the design of CMOS combinational and sequential functions at the gate level, including CMOS memory. CMOS transistor theory is covered including: DC equations, threshold voltage, body effect, subthreshold region, channel length modulation, tunneling, and punch through. A basic exposure to VLSI includes: CMOS processing technology, layout, and CMOS logic design including power, delay and timing considerations. Students will use industry standard Computer Aided Design tools to verify designs and layouts."));


    courseList.add(Courses(category: "Computer Science",subcategory: "Networking", no: "CSC 8", name: "Introduction to Internet Technologies", prerequisite: "Basic computer literacy recommended.", semester: "Summer only", skills: "Internet applications such as email, instant messaging, file transfer, secure communications, the web, and related tools and protocols. Basics of the web-publishing process and methods used to locate authoritative information on the internet. Webpage design, internet security and emerging technologies on the internet."));
    courseList.add(Courses(category: "Computer Science",subcategory: "Networking", no: "CSC 138", name: "Computer Networking Fundamentals", prerequisite: "CSC 60, CSC 130. Not currently enrolled in CSC/CPE 138.", semester: "Fall, Spring", skills: "Overview, structure, models, concepts, principles and protocols of computer networking. Network architecture, ISO/OSI reference model, TCP/IP protocol stack, layering. Protocol, encapsulation, socket. HTTP, FTP, SMTP, DNS, P2P, TCP, UDP. Multiplexing and demultiplexing, reliable data transfer, flow control, congestion control. Internet addressing, routing, forwarding, IP, ICMP. Error detection and correction, multiple access problem, LAN vs WAN, Ethernet, ARP, switching. Wireless standards. Network security, threats and attacks, defense and countermeasures."));
    courseList.add(Courses(category: "Computer Science",subcategory: "Networking", no: "CSC 255", name: "Computer Networks", prerequisite: "Graduation", semester: "Fall, Spring", skills: "Computer networking fundamentals with emphasis on higher level protocols and functions. Network design considerations, software design and layering concepts, interface design, routing and congestion control algorithms, internetworking, transport protocol design, and end-to-end communication, session and application protocols. Specific examples of commercial and international standards."));
    courseList.add(Courses(category: "Computer Engineering",subcategory: "Networking", no: "CPE 138", name: "Computer Networking Fundamentals", prerequisite: "CSC 35, CSC 60, CSC 130. Not currently enrolled in CSC/CPE 138.", semester: "Fall, Spring", skills: "Overview, structure, models, concepts, principles and protocols of computer networking. Network architecture, ISO/OSI reference model, TCP/IP protocol stack, layering. Protocol, encapsulation, socket. HTTP, FTP, SMTP, DNS, P2P, TCP, UDP. Multiplexing and demultiplexing, reliable data transfer, flow control, congestion control. Internet addressing, routing, forwarding, IP, ICMP. Error detection and correction, multiple access problem, LAN vs WAN, Ethernet, ARP, switching. Wireless standards. Network security, threats and attacks, defense and countermeasures.Cross Listed: CSC 138; only one may be counted for credit."));

    courseList.add(Courses(category: "Computer Science",subcategory: "Database", no: "CSC 134", name: "Database Management Systems", prerequisite: "CSC 130, and not currently enrolled in CSC 134", semester: "Fall, Spring", skills: "Entity-Relationship (ER) model; relational model; relational database design by ER-to-relational mapping; design of applications using database technology; SQL; schema definition, constraints, and queries; relational algebra; data normalization; access methods such as indexing and hash structures; introduction to transaction processing."));
    courseList.add(Courses(category: "Computer Science",subcategory: "Database", no: "CSC 122", name: "Web Database Applications.", prerequisite: "CSC 10 or CSC 22; and CSC 80 or equivalent.", semester: "Fall, Spring", skills: "Fundamentals of building effective database-driven web applications. Particular emphasis on database access via web interfaces. Introduction to database management systems, their structure and usage, SQL, integrating web applications with databases, design and implementation of dynamic web database applications."));

    courseList.add(Courses(category: "Computer Science",subcategory: "Animation", no: "CSC 127", name: "3D Computer Animation", prerequisite: "ART 142 or CSC 126.", semester: "Spring only", skills: "Creative skills and techniques for animating 3D computer-modeled objects/environments. Topics include animation techniques; keyframing and interpolation; deformation and morphing; path control; skeletal animation; model rigging and skinning; forward and inverse kinematics, constraints and IK solvers; particle systems; fluid, cloth, hair, and fur simulation; shape keys; and soft body animation. Emphasis on both skill development and creative application of modeling and animation techniques. Includes demos, in class and homework excercises, and self directed projects."));
    courseList.add(Courses(category: "Computer Science",subcategory: "Animation", no: "CSC 126", name: "3D Computer Modeling", prerequisite: "CSC 10 or ART 97 or equivalent.", semester: "Fall only", skills: "Techniques and processes to create 3D computer models and environments. Exercises, assignments and projects designed to build skill levels with 3D computer modeling tools. Demonstrations and workshops in the use of 3D computer modeling software. Critiques, discussion and presentations to develop students' conceptual grasp of 3D computer modeling and virtual reality environments. Example applications in art/new media and computer gaming."));


    courseList.add(Courses(category: "Computer Engineering",subcategory: "Programming", no: "CPE 64", name: "Introduction to Logic", prerequisite: " CSC 15 or CSC 25 or ENGR 50", semester: "Fall, Spring, Summer", skills: "Covers the following topics: logic gates, binary number system, conversion between number systems, Boolean algebra, Karnaugh maps, combinational logic, digital logic design, flip-flops, programmable logic devices (PLDs), counters, registers, memories, state machines, designing combinational logic and state machines into PLDs, and basic computer architecture. Lab emphasizes the use of software equation entry design tools, the use of a schematic entry, and the use of a logic simulation design tool. Lab assignments are design-oriented. Lecture three hours; laboratory three hours."));
    courseList.add(Courses(category: "Computer Science",subcategory: "Programming", no: "CSC 10", name: "Introduction to Programming Logic", prerequisite: "Math 11 or equivalent", semester: "Fall, Spring", skills: "Introduction to computer science with an emphasis on programming concepts and methodology. Intended to assist students with little or no programming experience to understand the basic principles of programming logic. Topics include computer hardware and software, problem solving and algorithm development, flow of control, modular design using techniques that can be applied to common programming languages. Lecture two hours, technical activity and laboratory two hours."));
    courseList.add(Courses(category: "Computer Science",subcategory: "Programming", no: "CSC 15", name: "Programming Concepts and Methodology I", prerequisite: "CSC 10, or programming experience in a high-level programming language. Not currently enrolled in CSC 15.", semester: "Fall, Spring, Summer", skills: "Programming concepts using an object-oriented programming language. Introduction to methodologies for program design, development, testing, and documentation. Topics include program design, algorithm design, number systems, classes and objects, methods (functions), control structures, arrays, and interactive input/output. Lecture two hours, technical activity and laboratory two hours."));
    courseList.add(Courses(category: "Computer Science",subcategory: "Programming", no: "CSC 22", name: "Visual Programming in BASIC", prerequisite: "-", semester: "Fall, Spring", skills: "Computer Programming using Visual Basic. Topics include the Visual Basic Integrated Development Environment, visual user interface development, concepts of object-oriented programming, variables, control structures, arrays, functions, subroutines, strings, files, and database access. Applications will be created in areas such as business, games, and multimedia. Lecture two hours, technical activity and laboratory two hours."));
    courseList.add(Courses(category: "Computer Science",subcategory: "Programming", no: "CSC 25", name: "Introduction to C Programming", prerequisite: "-", semester: "Fall", skills: "Topics include: types, operators, control structures, input/output, arithmetic operations, the C library and preprocessor, functions and parameters, arrays, strings, pointers, and structures. Program design and style will be emphasized. Students will use a compiler."));

    courseList.add(Courses(category: "Civil Engineering",subcategory: "Geotechnical Modeling", no: "CE 272", name: "Geotechnical Modeling", prerequisite: "CE 170 and CE 170L or equivalent.", semester: "Spring only – even years", skills: "Advanced analysis principles and procedures for calculating monotonic and cyclic soil element response effective stress and pore water pressure distributions, dynamic site response, and soil deformations; application to analysis of complex geotechnical engineering systems such as levees, dams, and wharfs. Laboratory time devoted to numerical analysis software and physical element and small scale tests. Lecture two hours. Laboratory three hours."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Geotechnical Modeling", no: "CE 170", name: "Soil Mechanics", prerequisite: "CE 1, CE 100, CE 101, ENGR 112, and CE 170L. CE 170L may be taken concurrently. CE 101 may be taken concurrently. Not currently enrolled in CE 170.", semester: "Fall, Spring", skills: "Composition and properties of soils; soil classification; soil compaction; soil-water interaction, including permeability and seepage analyses; soil stresses; soil compressibility, consolidation, and settlement analysis; soil shear strength."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Geotechnical Modeling", no: "CE 171", name: "Soil Mechanics and Foundation Engineering", prerequisite: " CE 170 and CE 170L. Not currently enrolled in CE 171", semester: "Spring", skills: "Lateral earth pressures and principles of retaining wall design; slope stability analysis and principles of slope stabilization design; ultimate bearing capacity of soils, allowable bearing pressures and settlement of structures; principles of foundation design including shallow foundations and deep foundations."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Geotechnical Modeling", no: "CE 175", name: "Geotechnical Earthquake Engineering", prerequisite: "CE 170.Not currently enrolled in CE 175.", semester: "Fall", skills: "Introduction to seismology and seismic hazard analysis; determination of building code design loads; prediction of soil-site effects; evaluation of liquefaction triggering, cyclic softening and associated consequences; introduction to mitigation techniques for liquefaction and ground failure hazards."));

    courseList.add(Courses(category: "Civil Engineering",subcategory: "Graphics and CAD", no: "CE 4", name: " Engineering Graphics and CAD", prerequisite: "Understanding Personal Development (E)", semester: "Fall, Spring", skills: "In-depth graphic analysis and solution of typical three dimensional space problems by applying the principles of orthogonal projection. Fundamentals of interactive computer aided design and drafting. Lecture one hour; laboratory three hours"));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Graphics and CAD", no: "CE 133", name: "Design of Urban Water and Sewer Systems", prerequisite: "CE 130 and CE 130L. Not currently enrolled in CE 133.", semester: "Fall", skills: "Hydraulic design of water distribution and sewerage systems. Computer-assisted pipe network analysis. Analysis of pump systems. Pump station design. Other selected topics."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Graphics and CAD", no: "CE 144", name: "Geometric Design of Highways.", prerequisite: "CE 140, CE 140L", semester: "Fall,Spring", skills: "Theory and practice of the principles of geometric design of highways and roads focusing on designing visual aspects of highways, highway classification, design controls and criteria, design elements, safety, vertical and horizontal alignment, cross section, intersections, and interchanges. Emphasis on the latest Federal and California design standards and tools, methods, and practices."));

    courseList.add(Courses(category: "Civil Engineering",subcategory: "Transportation", no: "CE 140", name: "Transportation Engineering", prerequisite: "CE 1, CE 9, CE 9L, CE 101, ENGR 115, and CE 140L. CE 140L may be taken concurrently. CE 101 may be taken concurrently. Not currently enrolled in CE 140", semester: "Fall,Spring", skills: "Introduction to the fundamental topics in Transportation Engineering. Focus on roadway geometric design, layout considerations, pavement materials and design, traffic operations and analysis."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Transportation", no: "CE 142", name: "Transportation Systems", prerequisite: "CE 140. Not currently enrolled in CE 142", semester: "Fall", skills: "Transportation systems evaluation and management. Focus on transportation planning methods, including data analysis, estimation of future demand, evaluation of travel demand impacts on existing systems, and transportation system decision-making."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Transportation", no: "CE 242", name: "Transportation Planning", prerequisite: "CE 142", semester: "Fall", skills: "Introduction to the complexities of comprehensive intermodal transportation planning. Study of transportation problems, system operating characteristics, alternative modes, and the planning process. Analyzes factors affecting travel behavior and methods of forecasting demand for travel by various modes."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Transportation", no: "CE 244", name: "Advanced Transportation Facility Design", prerequisite: "CE 140", semester: "Fall", skills: "Advanced study of current topics in highway and mass transportation facility design including safety, curve design, pavement design and drainage facility design. Focuses on current design practice and recent or impending changes in design practice."));


    courseList.add(Courses(category: "Civil Engineering",subcategory: "Structural", no: "CE 160", name: "Introduction to Structural Analysis", prerequisite: "CE 1.Not currently enrolled in CE 160", semester: "Fall,Spring", skills: "Analysis of statically determinate and indeterminate beams, frames, and trusses. Includes energy principles, flexibility and stiffness analyses, and influence lines. Computers are used to aid in the solution of complex structural problems."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Structural", no: "CE 163", name: "Structural Steel Design.", prerequisite: "CE 160. Not currently enrolled in CE 163", semester: "Fall,Spring", skills: "Theory and practice in design of structural steel members and connections using current design specifications. Design of tension and compression members, laterally supported and unsupported beams, beam-columns, and bolted and welded connections."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Structural", no: "CE 267", name: "Structural Systems for Buildings", prerequisite: " CE 163, CE 164, and CE 166; or equivalent", semester: "Spring", skills: "Analysis and design of structural systems for buildings including frames, shear walls, and tubes; interaction between structural systems; secondary effects including geometric and material nonlinearities."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Structural", no: "CE 262", name: "Nonlinear Structural Analysis", prerequisite: "CE 260", semester: "Spring", skills: "Theory and applications of nonlinear structural analysis including geometric and material nonlinear effects. Stability issues and second-order analysis methods are discussed in the context of moment amplification effects, member buckling, and the behavior of structural elements and frames undergoing large deformations. Inelastic material behavior and stress resultant plasticity concepts within a line-type element framework. Computer implementation of geometric nonlinear behavior."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Structural", no: "CE 260", name: "Matrix Structural Analysis", prerequisite: "CE 160", semester: "Fall", skills: "Flexibility and stiffness methods of structural analysis are applied to two- and three-dimensional framed structures. Use of computer software to perform analysis is discussed in detail. Techniques of computer modeling are discussed."));

    courseList.add(Courses(category: "Civil Engineering",subcategory: "Environmental", no: "CE 230", name: "Water Resources Planning", prerequisite: "CE 281", semester: "Fall", skills: "Application of single and multi-objective planning to the design and operation of water resources projects. Objectives and constraints for water projects, criteria and procedures for evaluation, planning under uncertainty. Application in water development and water quality planning, with case studies."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Environmental", no: "CE 232", name: "Groundwater Hydrology", prerequisite: "CE 130", semester: "Fall", skills: "Occurrence and movement of groundwater; physical characteristics of aquifers; analysis of steady-state groundwater flow problems by mathematical, digital computer, electrical analog and graphical methods; analysis of unsteady-state problems in confined and unconfined, aquifers; multiple well systems."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Environmental", no: "CE 254", name: "Water Quality Management", prerequisite: "CE 170", semester: "Fall,Spring", skills: "Examination of pollution sources and effects on water bodies, and the management issues and tools used to protect environmental quality. Topics include point and nonpoint pollution sources, interactions in the environment, Federal and State laws, water quality objectives, beneficial uses, and regulatory mechanisms such as basin plans and total maximum daily loads (TMDLs). Emphasis is on surface water."));
    courseList.add(Courses(category: "Civil Engineering",subcategory: "Environmental", no: "CE 255", name: "Transport of Chemicals in Soil Systems", prerequisite: "MATH 45", semester: "Fall,Spring", skills: "Study of the mechanics of movement of chemicals in soil, including equilibrium and partition models, development of mass transport equations in porous media, analytical solution for one-dimensional transport, lumped parameter transport model (linear reservoir model), transport of reactive and conservative chemicals numerical solutions of transport models, transport in the unsaturated zone and coupled models for saturated and unsaturated zone."));

    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Logical & Circuit Design", no: "EEE 64", name: "Introduction to Logic Design", prerequisite: "CSC 15 or CSC 25 or ENGR 50", semester: "Fall,Spring,Summer", skills: "Covers the following topics: logic gates, binary number system, conversion between number systems, Boolean algebra, Karnaugh maps, combinational logic, digital logic design, flip-flops, programmable logic devices (PLDs), counters, registers, memories, state machines, designing combinational logic and state machines into PLDs, and basic computer architecture. Lab emphasizes the use of software equation entry design tools, the use of a schematic entry, and the use of a logic simulation design tool. Lab assignments are design-oriented."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Logical & Circuit Design", no: "EEE 196", name: "PCB Design Fundamentals", prerequisite: "EEE 102, CPE 102 or EEE 108.", semester: "Fall,Spring", skills: "Printed circuit board (PCB) design fundamentals including library component creation, schematic capture, layout, routing, signal integrity and transmission line analysis, IEEE/IPC rules and standards, materials, manufacturing processes, and other physical properties of a PCB."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Logical & Circuit Design", no: "EEE 230", name: "Analog and Mixed Signal Integrated Circuit Design.", prerequisite: "EEE 109 or instructor permission", semester: "Fall", skills: "A companion course to EEE 230, covers additional topics important in analog and mixed-signal integrated circuit design. Topics include traditional issues such as device matching and analog layout techniques, as well as important building blocks such as bandgap references and bias circuits. Also included are current-mode techniques such as high-speed current-mode logic (CML), and an introduction to noise in integrated circuits. Circuit and layout projects are assigned using CAD software."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Logical & Circuit Design", no: "EEE 231", name: "Advanced Analog and Mixed Signal Integrated Circuit Design.", prerequisite: "EEE 230 or consent of the instructor.", semester: "Fall,Spring", skills: "Covers core topics and circuits important for analog and mixed-signal integrated circuits. Topics include: device structures and models, single-stage and differential amplifiers, current mirrors and active loads, operational amplifier design, stability and compensation, fully-differential circuits and common-mode feedback, noise in integrated circuits and the impact of IC processes on analog performance."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Logical & Circuit Design", no: "EEE 232", name: "Key Mixed-Signal Integrated Circuit Building Blocks.", prerequisite: "EEE 230 or consent of the instructor.", semester: "Spring", skills: "Covers key mixed-signal integrated circuit building blocks most often used in modern ICs. Topics covered include data converter fundamentals, comparators, and important circuit architectures for Analog-to-Digital Converters (ADCs), Digital-to-Analog Converters (DACs), and Phase-Locked Loops (PLLs)."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Logical & Circuit Design", no: "EEE 234", name: "Digital Integrated Circuit Design", prerequisite: "EEE 230 or consent of the instructor.", semester: "Fall,Spring", skills: "The background and techniques needed to design and layout digital circuits at the transistor level for mixed-signal integrated circuits are covered. Topics include the design, layout and characterization of digital logic gates at the transistor level, typical CMOS process flows, device models and physics, and chip level considerations."));


    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Communication", no: "EEE 183", name: "Digital and Wireless Communication System Design.", prerequisite: "CEEE 161, EEE 180; EEE 185 may be taken concurrently.", semester: "Fall", skills: "Review of fundamentals, probability, information, distortion by channel, sampling, pulse code modulation, companding, link power calculation, noise figure, pseudo noise. Matched filter detection of binary signals, bit error rate, inter-symbol interference, zero-forcing equalizers. Effects of additive white Gaussian noise in pulse code modulation, spread spectrum in multiple access, cellular radio and other wireless applications. Procedure for making design trade offs will be discussed."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Communication", no: "EEE 185", name: "Modern Communication Systems.", prerequisite: "EEE 180, ENGR 120; ENGR 120 may be taken concurrently.", semester: "Fall,Spring", skills: "Review of signal and system analysis, sampling theorem and Nyquist's criteria for pulse shaping, signal distortion over a channel, study of digital and analog communication systems, line coding, signal to noise ratios, performance comparison of various communication systems."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Communication", no: "EEE 186", name: "Communication Systems Laboratory.", prerequisite: "EEE 117 (EEE 185 may be taken concurrently), and (GWAR Certification before Fall 09, or WPJ score of 70+, or at least a C- in ENGL 109M or ENGL 109W).", semester: "Fall,Spring", skills: "Experimental study of modulation and demodulation in AM, FM, and digital communication systems, A/D and D/A conversion, measurement of power spectra, noise characterization in frequency domain."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Communication", no: "EEE 241", name: "Linear Systems Analysis", prerequisite: "EEE 180", semester: "Spring", skills: "Analyzes linear systems in the state-space. System realization and modeling, solutions of linear systems, stability including the method of Lyapunov, controllability and observability, state feedback and observers for both continuous and discrete-time systems. Familiarity with MATLAB is required."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Communication", no: "EEE 242", name: "Statistical Signal Processing", prerequisite: "EEE 180", semester: "Fall,Spring", skills: "Introduces the student to modern statistical approaches for solving electronic system noise problems. A few of the topics covered are: Stochastic processes, Wiener and Kalman filters, linear prediction, lattice predictors and singular-value decomposition."));


    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Robotics & Machine Learning", no: "EEE 187", name: "Robotics", prerequisite: "EEE 180 or equivalent, or instructor permission.", semester: "Fall", skills: "Lecture introduces principles of robotics and design of robot systems. Includes robot architectures, sensing position/velocity, digital circuit noise, actuator and path control, robot coordinate systems, kinematics, differential motion, computer vision/architectures, and artificial intelligence. Laboratory will apply lecture theory in design experiments utilizing five degree-of-freedom robots, an industrial robot, and vision systems."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Robotics & Machine Learning", no: "EEE 178", name: "Introduction to Machine Vision", prerequisite: "EEE 180 or ME 172, or instructor approval.", semester: "Spring", skills: "Fundamental digital image processing and machine vision concepts and their application to the fields of robotics and automation. Topics include: digital image processing, image formation, two dimensional transforms, boundary descriptors, motion, camera calibration, vision for robot control, 3-D vision, and hardware architectures to support vision."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Robotics & Machine Learning", no: "EEE 221", name: "Machine Vision", prerequisite: "-", semester: "Spring", skills: "Introduces the student to fundamental digital imaging processing concepts and their application to the fields of robotics, automation, and signal processing. Topics include: digital image filters, two dimensional transforms, boundary descriptors, Hough transform, automated visual inspection techniques, vision for robot control, 3-D vision, and hardware architectures to support vision."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Robotics & Machine Learning", no: "EEE 225", name: "Advanced Robot Control", prerequisite: "EEE 184 or equivalent.", semester: "Fall", skills: "Introduction to robot kinematics and dynamics followed by a comprehensive treatment of robot control. Topics include: independent joint control, multivariable control, force control, feedback linearization, real-time parameter estimation, and model-reference adaptive control."));
    courseList.add(Courses(category: "Electrical Engineering",subcategory: "Robotics & Machine Learning", no: "EEE 236", name: "Advanced Semiconductor Devices", prerequisite: "-.", semester: "Spring", skills: "Semiconductor device modeling, including the application of the continuity equation and Poissons equation to abrupt and graded p/n junctions, semiconductor/metal contacts, junction field effect transistors (JFET), metal-oxide-semiconductor transistors (MOSFET), and bipolar junction transistors (BJT). Special topics include compound semiconductor devices and heterostructures."));

    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Maintenance", no: "ME 37", name: "Manufacturing Processes.", prerequisite: "-", semester: "Fall,Spring,Summer", skills: "Principles of manufacturing processes in the areas of metal removal, forming, joining and casting and fundamentals of numerical control. Study includes applications of equipment, e.g., lathe, milling machine, drill press, saw, grinder, welder, molding equipment and core makers. Emphasis on safety during hands-on operations. Two hours lecture, one three-hour lab."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Maintenance", no: "ME 136", name: "Numerical Control Programming.", prerequisite: "ME 37 and ME 105; ME 105 may be taken concurrently.", semester: "Fall,Spring", skills: "Computer programming languages for automated manufacturing, including CNC manual programming, cutter compensation, geometric definition of products, cutting tool definition, continuous path part programming, computation, decision, looping, computer graphics programming and intelligent machines."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Maintenance", no: "ME 164", name: "Introduction to Test Automation.", prerequisite: "ME 105 and ME 117", semester: "Fall,Spring", skills: "Basic concepts to automate testing procedures. Introduction to sensors, signal conditioning, sampling theory, design of experiments, data acquisition software, and data reduction techniques. Hands-on experience with PC based data acquisition software and hardware which will be used to create testing programs. Lecture two hours; laboratory three hours."));

    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "CAD Technician", no: "ME 176", name: "Product Design & CAD", prerequisite: "ENGR 6, ME 105 and ME 116", semester: "Fall,Spring", skills: "Digital product development using an integrated CAD system. Philosophy of parametric design. Component and assembly design, basic drawing creation, and simulations. Team product design investigating the effects of variations in geometry, dimensions, and material selection. Lecture two hours; laboratory three hours."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "CAD Technician", no: "ME 177", name: "Product Design and 3D Parametric Solid Modeling.", prerequisite: "ENGR 6, ME 105 and ME 116", semester: "Fall,Spring", skills: "Introduction to Solid Modeling and its application to mechanical product design. Digital product development using 3D Parametric Solid Modeling tools. Also covers component and assembly design, basic drawing creation. Reverse design project engineering investigating the effects of variations in geometry, dimensions, and material selection. Lecture two hours; laboratory three hours."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "CAD Technician", no: "ME 296", name: "Advanced CAD for Aerospace Applications", prerequisite: "-", semester: "Fall,Spring", skills: "Design of aerospace systems including profile definition, constraints, operations and visualizations, component design, transformation features, and insertions using advanced CAD software such as CATIA. Creation of complete assembly design including creation of product files, identifying, inserting and displacing components, constraining parts, numbering parts and scene creation. Specifics of sheet metal design for aerospace design including creation of flange, cut-out, joggle, holes, stampings and patterns."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "CAD Technician", no: "ME 295", name: "Fieldwork", prerequisite: "Permission of Graduate Coordinator or Department Chair.", semester: "Fall,Spring", skills: "Supervised employment in industry or government that provides practical work experience. Requires satisfactory completion of the work assignment and a written report."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "CAD Technician", no: "ME 137", name: "Product Design for Manufacturing and Automation.", prerequisite: "ME 117", semester: "Fall,Spring", skills: "Various manufacturing and automation aspects of product design, including design for machining, design for automation, applications of CAD/CAM software in product design and automation, and rapid prototyping. Virtual design and manufacturing and agile manufacturing will also be discussed."));

    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Aerospace & Vehicle-Machine Design", no: "ME 275", name: "Analysis of Aircraft Structures.", prerequisite: "Graduate", semester: "Fall,Spring", skills: "Review of structural analysis: elasticity, virtual work and energy methods, torsion of solid sections, bending of plates, columns. Analysis of aircraft structures: materials, structural components of aircraft, airworthiness, airframe loads, fatigue, structural idealization, fuselages, wings."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Aerospace & Vehicle-Machine Design", no: "ME 278", name: "Space Systems Engineering Management.", prerequisite: "Graduate", semester: "Fall,Spring", skills: "Systems Engineering approach to plan and direct engineering projects. Emphasizes systems engineering process, requirement design fundamentals, subsystem fundamentals, trade studies, integration, technical reviews, case studies and ethics. Space exploration used as an example; skills applicable to any engineering project. Project-orientated course to plan the design of space and ground vehicles, satellites, airplanes and multidisciplinary subsystems."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Aerospace & Vehicle-Machine Design", no: "ME 297", name: "Space Mission Design and Analyses.", prerequisite: "Graduate", semester: "Fall,Spring", skills: "This course examines the methods of systems design and analyses required to design and optimize the space mission over its life cycle. The process of optimization covers all the major elements of a space mission such as the ground systems, launch vehicles, spacecraft/payload, space environment, in-orbit operation and maintenance, and end-of-life disposal. The optimization of the overall mission must balance between performance, cost and reliability of all the major elements."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Aerospace & Vehicle-Machine Design", no: "ME 298", name: "Advanced Computer-Aided Product Design.", prerequisite: "Graduate", semester: "Fall,Spring", skills: "Advanced topics in computer-aided design and applications for mechanical product design. Reviews of fundamental parts, assembly modeling, and engineering drawings. Advanced modeling topics such as surface modeling, design for manufacturing, simulation-based design, top-down assembly, macros and API programming."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Aerospace & Vehicle-Machine Design", no: "ME 143", name: "Vehicle Dynamics and Design.", prerequisite: "ME 117", semester: "Fall,Spring", skills: "Principles and practice in vehicle dynamics and design using computer aided techniques. Design methods for passenger vehicles, SUVs, trucks, motorcycles and space vehicles. Study of tires, drivetrain and gear boxes in ground vehicles. Kinematics and kinetics of mechanisms in two and three dimensions with applications to suspensions, steering mechanisms. Frame design using finite element analysis, power trains, braking, auxiliary systems. Computer dynamic models for analysis of vehicle stability, collisions rollovers, and failure analysis using state-of-the-art software."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Aerospace & Vehicle-Machine Design", no: "ME 152", name: "Turbomachinery Design.", prerequisite: "ME 120", semester: "Fall,Spring", skills: "Theoretical analysis of energy transfer between fluid and rotor; principles of axial, mixed, and radial flow compressors and turbines. Applications and computer-aided design of various types of turbomachines."));

    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Energy and Quality Analyst", no: "ME 121", name: "Solar Thermal and Energy Storage Systems.", prerequisite: "ENGR 124.", semester: "Fall,Spring", skills: "Study of solar thermal heat and power and energy storage including the characterization, theory, operation, analysis and modeling of solar thermal and energy storage systems."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Energy and Quality Analyst", no: "ME 123", name: "Wind, Hydro and Ocean Energy", prerequisite: "ENGR 124.", semester: "Fall,Spring", skills: "Exploring sustainable energy and power generation, through study of wind, hydro and ocean energy systems, including the characterization, theory, operation, analysis, modeling, planning impacts and design process."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Energy and Quality Analyst", no: "ME 126", name: "Heat Transfer.", prerequisite: "ENGR 124.", semester: "Fall,Spring", skills: "Basic principles of heat transfer, including processes of conduction, convection, radiation, evaporation and condensation. Lecture three hours."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Energy and Quality Analyst", no: "ME 129", name: "Power Plant Engineering.", prerequisite: "Thermodynamics (ENGR 124) and Thermal-Fluid Systems (ME 128). ME 128 may be taken concurrently", semester: "Fall,Spring", skills: "In this course, the students will be able to understand the fundamentals of power industry, including electricity production, transmission, and distribution. They will also apply their engineering knowledge gained in the fundamental courses to understand and conceptually design various modern power plant technologies for electric power generation and cogeneration, including steam power plants, gas turbines, combined cycles, and nuclear power plants and their components."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Energy and Quality Analyst", no: "ME 132", name: "Solar Energy, Geothermal Energy, and Bioenergy Systems.", prerequisite: "ENGR 124.", semester: "Fall,Spring", skills: "In this course, the students will study solar energy, geothermal energy, and bioenergy systems. They will apply their engineering knowledge gained in the fundamental courses to design these systems. They will also learn about theoretical foundations, characterization, operation, and environmental impacts of these energy systems."));
    courseList.add(Courses(category: "Mechanical Engineering",subcategory: "Energy and Quality Analyst", no: "ME 140", name: "Introduction to Motors and Actuators.", prerequisite: "ME 172.", semester: "Fall,Spring", skills: "Power conversion hardware used in electromechanical systems. Operation and sizing of electric motors, both DC and AC systems, motor controllers, and power electronics; sensors; design in fluid power systems, both pneumatic and hydraulic; and power transmission systems such as ball screws and belt drivers."));




    courseList.shuffle();
    if(Get.arguments[1] !=null){
      if(Get.arguments[1]=="Computer Science" || Get.arguments[1]=="Computer Engineering"){
        courseList.forEach((element) {
          if(element.subcategory=="Design"){
            listOne.add(element);
          }
          if(element.subcategory=="Programming"){
            listTwo.add(element);
          }
          if(element.subcategory=="Database"){
            listThree.add(element);
          }
          if(element.subcategory=="Animation"){
            listFour.add(element);
          }
          if(element.subcategory=="Networking"){
            listFive.add(element);
          }

        });
      }
      else if(Get.arguments[1]=="Civil Engineering"){
        courseList.forEach((element) {
          if(element.subcategory=="Geotechnical Modeling"){
            listOne.add(element);
          }
          if(element.subcategory=="Graphics and CAD"){
            listTwo.add(element);
          }
          if(element.subcategory=="Transportation"){
            listThree.add(element);
          }
          if(element.subcategory=="Structural"){
            listFour.add(element);
          }
          if(element.subcategory=="Environmental"){
            listFive.add(element);
          }

        });
      }
      else if(Get.arguments[1]=="Electrical Engineering"){
        courseList.forEach((element) {
          if(element.subcategory=="Logical & Circuit Design"){
            listOne.add(element);
          }
          if(element.subcategory=="Communication"){
            listTwo.add(element);
          }
          if(element.subcategory=="Robotics & Machine Learning"){
            listThree.add(element);
          }
        });
      }
      else if(Get.arguments[1]=="Mechanical Engineering"){
        courseList.forEach((element) {
          if(element.subcategory=="Energy and Quality Analyst"){
            listOne.add(element);
          }
          if(element.subcategory=="Aerospace & Vehicle-Machine Design"){
            listTwo.add(element);
          }
          if(element.subcategory=="CAD Technician"){
            listThree.add(element);
          }
          if(element.subcategory=="Maintenance"){
            listFour.add(element);
          }
        });
      }
    }



  }
  


}